tensor-compiler/taco

- src/backends/codegen_c.cpp
- src/ir/ir.cpp
- src/ir/ir.h
- src/ir/ir_printer.cpp
- src/ir/ir_rewriter.cpp
- src/lower/lower.cpp
- src/storage/dense_iterator.cpp
- src/storage/fixed_iterator.cpp
- src/storage/sparse_iterator.cpp
This PR extends `GetProperty` in the backend IR to be able to access all parts of the `taco_tensor_t` struct.
> `GetProperty` extensions

- src/io/rb_file_format.cpp
- src/parser/parser.cpp
- src/storage/pack.cpp
This simple PR fixes INT_MAX undefined error on clang++ compiler(requires to include climits header)
> Fix INT_MAX undefined compilation error on clang++.

- include/taco/tensor.h
- src/tensor.cpp
- test/tensor-tests.cpp
#82 Simple transpose implementation for tensors by creating a new tensor from the values in a current tensor. This allows for arbitrarily reordering modes or changing the format of the output tensor. I am still working on a more efficient transpose algorithm that reuses structure from the input tensor.
> Simple Transpose

- src/ir/simplify.cpp
- test/tests-copyprop.cpp
The existing copy propagation has a bug handling situations like the following:
```
a = 0;
b = a;
c = b;
use(c);
```
which gets mis-simplified into
```
a = 0;
use(b); // should be `use(a)'
```
> Recursively propagate copies

- src/lower/lower_old.cpp
The lowerer currently emits zero statement by using hardcoded `0.0`. This can create unexpected issue when the tensors are not floats (e.g. integer). So far the problem hasn't surfaced because the C compiler we use silently converts the literal to the correct type.
> Emit zero literal per type

- include/taco/index_notation/index_notation.h
- src/index_notation/index_notation.cpp
- src/lower/merge_lattice_old.cpp
- test/tests-expr.cpp
Taco does not handle subtraction when there are non exhausted points in the merge lattice.
It generates code looking like this
```
// compute `a - b'
if (both_a_and_b())
t = a - b
else if (just_a())
t = a
else
// should be `t = -b'
t = b
```
> handle non-exhausted lp in subtraction

- README.md
- include/taco/cuda.h
- include/taco/util/collections.h
- src/codegen/codegen_cuda.cpp
- src/cuda.cpp
- src/lower/lower_old.cpp
- src/storage/array.cpp
- src/storage/file_io_rb.cpp
- src/taco_tensor_t.cpp
- src/type.cpp
- tools/taco.cpp
- Allow generating CUDA code even if taco is not built with CUDA (changes -no-gpu cli flag to -cuda flag)
- Use same parallelization preconditions as generating openmp pragmas
- Updated CUDA complex number support to use thrust/complex.h (preinstalled with CUDA >= 4.0)
(see issue #129  for more updates)
- CLI does not invoke system compiler unless code will be benchmarked
> CUDA Code Generation Update

- tools/taco.cpp
The command line tool is supposed to check if any directives were provided; if not, then `-print-compute` is the default. However, `-print-evaluate` was not properly checked so `-print-compute` was always printed alongside it. This fixes that.
> Do not do default -print-compute if -print-evaluate is present

- include/taco/index_notation/index_notation.h
- include/taco/index_notation/index_notation_nodes.h
- include/taco/index_notation/transformations.h
- include/taco/lower/iterator.h
- include/taco/tensor.h
- src/codegen/codegen_c.cpp
- src/index_notation/index_notation.cpp
- src/index_notation/index_notation_printer.cpp
- src/index_notation/index_notation_rewriter.cpp
- src/index_notation/kernel.cpp
- src/index_notation/transformations.cpp
- src/lower/iterator.cpp
- src/lower/lowerer_impl.cpp
- src/tensor.cpp
- test/tests-transformation.cpp
- tools/taco.cpp
Adds the parallelize scheduling command to allow for parallelizing loops that fit the preconditions specified in the original taco paper.
Instead of exposing the full scheduling language yet, this transformation is automatically applied before lowering. This allows taco v2 (#201) to produce the same type of parallel code that taco v1 could. In the future this command will be extended to allow some of the existing preconditions to be broken. #127 is out of date, but should track this progress going forward.
> Parallelize Scheduling Command

- include/taco/index_notation/transformations.h
- src/index_notation/transformations.cpp
- src/lower/iterator.cpp
- src/tensor.cpp
- test/tests-transformation.cpp
- tools/taco.cpp
Topologically reorders Concrete Index Notation so as to access tensors in order. This allows for TACO to generate efficient and correct code for expressions where the default iteration order is not correct. For example a {dense, dense, sparse, dense, dense} tensor has constraints i -> k, j -> k, k -> l, k -> m, but the pairs (i, j) and (l, m) can be reordered depending on other constraints. This code also checks for cycles in the dependencies and prints an error message to inform users that they must transpose one of the tensors (#197 tracks progress on a faster transpose implementation). In the future this transformation will be exposed in a scheduling language (#127).
> Topologically Reorder Concrete Index Notation

- CMakeLists.txt
- include/taco/parser/einsum_parser.h
- include/taco/parser/parser.h
- include/taco/tensor.h
- python_bindings/CMakeLists.txt
- python_bindings/include/pyParsers.h
- python_bindings/pytaco/__init__.py
- python_bindings/pytaco/numpy_license.txt
- python_bindings/pytaco/pytensor/__init__.py
- python_bindings/pytaco/pytensor/funcs.py
- python_bindings/pytaco/pytensor/taco_tensor.py
- python_bindings/pytaco/pytensor/tensorIO.py
- python_bindings/src/pyDatatypes.cpp
- python_bindings/src/pyIndexNotation.cpp
- python_bindings/src/pyParsers.cpp
- python_bindings/src/pyTensor.cpp
- python_bindings/src/pyTensorIO.cpp
- python_bindings/src/pytaco.cpp
- src/parser/einsum_parser.cpp
- src/parser/parser.cpp
Exposes parsers to Python and hides different tensor classes.
Implements a functional API for the python interface.
Exposes dense tensors as buffer objects so they can be transformed to numpy arrays.
Allows initialization of tensors from numpy arrays and scipy sparse matrices.
> Python bindings

- python_bindings/docs/make.bat
- python_bindings/docs/source/conf.py
- python_bindings/docs/source/index.rst
- python_bindings/docs/source/rst_files/as_np_dt.rst
- python_bindings/docs/source/rst_files/datatype.rst
- python_bindings/docs/source/rst_files/dtype_object.rst
- python_bindings/docs/source/rst_files/file_io.rst
- python_bindings/docs/source/rst_files/format.rst
- python_bindings/docs/source/rst_files/format_class.rst
- python_bindings/docs/source/rst_files/format_funcs.rst
- python_bindings/docs/source/rst_files/mode_format.rst
- python_bindings/docs/source/rst_files/sched.rst
- python_bindings/docs/source/rst_files/tensor.rst
Added docs folder. Needs sphinx, numpydocs and sphinx_rtd_theme.
Install Sphinx using:
apt-get install python3-sphinx
Install numpydoc using:
pip3 install numpydoc
Install Read the docs theme using:
pip3 install sphinx_rtd_theme
To build, cd into the docs directory and type:
make html
There are some premade docs in the html folder.
> Added docs folder

- include/taco/ir/ir_printer.h
- include/taco/util/scopedmap.h
- include/taco/util/timers.h
- include/taco/util/variadic.h
- src/lower/lowerer_impl.cpp
Fix compilation errors when compiling taco with clang.
- Explicitly include headers that are used implicitly. 
- Call taco::ir::conjunction in lower_impl.cpp with its full name to avoid ambiguity with std::conjunction.
> Fix clang compilation errors.

- src/cuda.cpp
I get the following after running the tests:
```
[----------] Global test environment tear-down
[==========] 805 tests from 271 test cases ran. (1075533 ms total)
[  PASSED  ] 805 tests.
YOU HAVE 10 DISABLED TESTS
Compiler bug at /home/infinoid/workspace/taco/taco/src/cuda.cpp:49 in gpuAssert
Please report it to developers
GPUassert: 4 driver shutting down /home/infinoid/workspace/taco/taco/src/cuda.cpp 68
Aborted
```
In cuda 9.0, cudaErrorCudartUnloading = 29.
In cuda 10.2, cudaErrorCudartUnloading = 4.
Using the enum name should work in both cases.
With the fix, I get:
```
[----------] Global test environment tear-down
[==========] 805 tests from 271 test cases ran. (1037539 ms total)
[  PASSED  ] 805 tests.
YOU HAVE 10 DISABLED TESTS
```
My cmake command was:
`cmake …
> Cuda error codes vary with cuda version; don't hardcode numbers.

- test/tests-scheduling.cpp
The Python build changes the way errors are reported; failed assertions become thrown exceptions.
The gtest framework has different macros to expect assertions vs exceptions, so tests which expect assertions are broken for Python builds.
When you try to run this:
```
cmake -DPYTHON=ON ../taco
make
bin/taco-test
```
Three tests fail.  The failures look like:
```
[ RUN      ] scheduling.dense_pos_error
Death test: stmt.pos(i, ipos, x(i))
Result: threw an exception.
Error msg:
[  DEATH   ] 
[  DEATH   ] /home/infinoid/workspace/taco/taco/test/tests-scheduling.cpp:728:: Caught std::exception-derived exception escaping the death test statement. Exception message: Error at /home/infinoid/workspace/taco/taco/src/index_notation/index_notation.cpp:1458 in pos:
[  DEATH   ]  Pos transformation is …
```
> Fix scheduling tests to catch exceptions properly for Python builds

- .gitignore
- python_bindings/CMakeLists.txt
Currently, cmake's `make install` rule ignores the python bindings.  CMake puts the built shared object directly into the pytaco source folder.
This patch stages the `.py` files and `.so` file in the build folder, and installs them during `make install`.  The results look like this:
```
/usr/local/lib
/usr/local/lib/libtaco.so
/usr/local/lib/pytaco
/usr/local/lib/pytaco/__init__.py
/usr/local/lib/pytaco/pytensor
/usr/local/lib/pytaco/pytensor/__init__.py
/usr/local/lib/pytaco/pytensor/taco_tensor.py
/usr/local/lib/pytaco/pytensor/tensorIO.py
/usr/local/lib/pytaco/core
/usr/local/lib/pytaco/core/core_modules.cpython-36m-x86_64-linux-gnu.so
```
The staging of `.py` and `.so` files in the build folder will be useful for fixing `make test`, which is next on my list.
> Teach cmake how to install python bindings

- CMakeLists.txt
Taco requires a minimum cmake version of 2.8.3.  But while I was testing #300, I found that taco doesn't actually build with cmake 2.8.3.  The libtaco library fails to link:
```
Linking CXX shared library ../lib/libtaco.so
/usr/bin/ld: cannot find -lPRIVATE
collect2: error: ld returned 1 exit status
src/CMakeFiles/taco.dir/build.make:1669: recipe for target 'lib/libtaco.so' failed
make[2]: *** [lib/libtaco.so] Error 1
CMakeFiles/Makefile2:103: recipe for target 'src/CMakeFiles/taco.dir/all' failed
make[1]: *** [src/CMakeFiles/taco.dir/all] Error 2
Makefile:110: recipe for target 'all' failed
make: *** [all] Error 2
```
Taco's build scripts use the "PRIVATE" library type.  This feature was introduced in cmake 2.8.12.
So, bump the requirement to 2.8.12.  (Note that 2.8.12 is still quite …
> Bump cmake requirement to cover features taco uses

- README.md
PR #299 moved the python shared object from the source folder to the build folder.  The README.md still gives instructions for adding the source folder to PYTHONPATH, which doesn't work any more.  Cmake now stages everything properly in the build folder, so we should use that instead.
(Thanks to @jwshi21 for pointing this out.)
> Update PYTHONPATH example in README.md

- README.md
Correct the minimum CMake version.
Use `<taco-directory>/build` more consistently.
Fix instructions for running Python tests directly.
Update TLDR to run all available tests, not just the C++ ones.
> More minor README.md updates

- include/taco/taco_tensor_t.h
The [comment at the top of `taco_tensor_t.h`](https://github.com/tensor-compiler/taco/blob/master/include/taco/taco_tensor_t.h#L2)  says it should be C99, not C++.  However, it includes a C++-only system header.
Update it to include the C99 equivalent, instead.  This allows C programs to call Taco-generated compute functions.
> Fix taco_tensor_t.h to be compatible with C99.

- test/CMakeLists.txt
This allows application projects to build with Taco using cmake without target name collisions.
Fixes: #271
This allows application projects to include a taco source directory in their CMake build, and have their own copy of the gtest framework without name conflicts.
> Rename CMake "gtest" library to "taco-gtest"

- include/taco/error/error_messages.h
- include/taco/index_notation/index_notation.h
- include/taco/tensor.h
- include/taco/util/name_generator.h
- src/error/error_messages.cpp
- src/index_notation/index_notation.cpp
- src/tensor.cpp
- src/util/name_generator.cpp
- test/tests-error.cpp
Add a sanity check to catch cases where multiple tensors are used with the same name.
Fixes #324.
Add a check to Tensor.compile() to match up Tensor names with IDs and catch name collisions.
Add "Tensor name collision." error string to error_messages.{cpp,h}.
Add an internal unique ID to `Tensor` and `TensorVar` objects.
Add a test case.
> Add Tensor name collision detection

- test/tests-format-mm-permute.cpp
This adds a disabled test case, which tests matrix multiply for various formats of Matrix.
The test case does A=BC, and tries all permutations of Dense, CSR, CSC, and COO.
It is disabled for now because it crashes.  Enable it to get some visibility into the current issues Taco is having with sparse matrix output.
> Add a test case for mixing sparse/dense formats in matrix multiply

- src/lower/iterator.cpp
- test/tests-scheduling-eval.cpp
- test/tests-scheduling.cpp
Fixes #274
This fixes two classes of build failure that happen on Ubuntu 16.04.
1.  gcc 5.4.0 fails to call the createAccessIterators member function properly
2.  gcc 5.4.0 can't decide between two constructors: Tensor(name, shape, Format) and Tensor(name, shape, ModeFormat)
Taco builds successfully on Ubuntu 16.04 with this patch.
I tested with -DOPENMP=ON and -DPYTHON=ON.   Issue #316 happened; otherwise all tests passed.  I did not test CUDA.
> Fix build failures on ubuntu 16.04

- include/taco/error.h
- src/error.cpp
- test/tests-error.cpp
- test/tests-scheduling.cpp
Previously, exceptions were used only when the Python bindings were enabled.  This meant that C++ applications could only handle errors gracefully when the Python bindings were enabled.
Change it to consistently use exceptions in all cases.
> Use exceptions for error reporting in all cases

- python_bindings/src/pyTensor.cpp
Fix a few instances of this build error in pytaco:
```
.../pyTensor.cpp:406:53: error: unknown type name 'nullptr_t'; did you mean 'std::nullptr_t'?
```
Apparently, `nullptr_t` is not part of the global namespace for clang.  (At least, not version 10 of clang.)
[This SO](https://stackoverflow.com/questions/33101264/should-nullptr-t-be-part-of-the-global-namespace) mentions including `<stddef.h>` or `<cstddef>`, but those didn't make a difference in this case.
> Fix python bindings when building with clang++-10

- tools/taco.cpp
Previously the `insideCall` flag was never set back to `false` when encountering `')'`, which made it unable to handle more than one commands correctly.
This PR fixes it and simplify the `insideCall` and `parsingExpr` flags to be a unified `parenthesesCnt` counter.
> Fix -s argument parsing in the command line tool

- src/codegen/module.cpp
This is useful for passing additional arguments to nvcc.
I did this because I wanted to force nvcc to use a specific version of g++.
Example: `TACO_NVCC="nvcc -ccbin g++-8"`
> Add TACO_NVCC var to complement TACO_NVCCFLAGS

- python_bindings/pytaco/pytensor/taco_tensor.py
- python_bindings/unit_tests.py
This PR addresses issue #342.
It adds negation to the python tensor interface and adds a unit test for this.
> Adds negation to pytaco tensor interface

- src/index_notation/provenance_graph.cpp
- src/lower/lowerer_impl.cpp
Fix a few compilation warnings caused by taking copies of loop variables
instead of references.
> lower,index_notation: fix compilation warnings

- CMakeLists.txt
Building Taco with CUDA support causes cmake to warning, with cmake version 3.12.0 and later.  Here's what it looks like:
```
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON=ON -DOPENMP=ON -DCUDA=ON ../git
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/CMakeDetermineCompilerId.cmake:72 (if):
Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
Quoted variables like "CUDA" will no longer be dereferenced when the policy
is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
/usr/share/cmake-3.18/Modules/CMakeDetermineCCompiler.cmake:116 …
```
> Silence a warning about cmake policy CMP0054.

- include/taco/index_notation/index_notation.h
- include/taco/ir/ir.h
- include/taco/ir/ir_printer.h
- include/taco/ir/ir_rewriter.h
- include/taco/ir/ir_visitor.h
- include/taco/lower/lowerer_impl.h
- src/codegen/codegen_c.cpp
- src/codegen/codegen_cuda.cpp
- src/index_notation/index_notation.cpp
- src/index_notation/index_notation_printer.cpp
- src/index_notation/transformations.cpp
- src/ir/ir.cpp
- src/ir/ir_printer.cpp
- src/ir/ir_rewriter.cpp
- src/ir/ir_visitor.cpp
- src/lower/lower.cpp
- src/lower/lowerer_impl.cpp
- test/tests-scheduling.cpp
- test/tests-workspaces.cpp
This PR is joint work by myself and @weiya711. 
List of new features:
1. Support for hoisting allocation of workspace memory outside of the workspace loop. (Thanks to @weiya711)
2. Allows TACO to 'accelerate' dense workspace with sparse iteration. That is, if a workspace consumer is dense and is being stored in a sparse result TACO will automatically track a list of indices and only append the relevant indices to the result tensor. This is useful for SpGEMM. For now, this is only enabled for serial CPU code.
3. Changes the cuda and c code generators so that unique names are not generated for pointer variables.
4. Adds some tests for workspaces which exposed the bug below. (Thanks to @weiya711).
Addresses the following bugs:
1. Fixes bug causing derived variables on the RHS of an …
> Workspace reuse

- include/taco/parser/schedule_parser.h
- src/parser/schedule_parser.cpp
- test/tests-schedule-parser.cpp
- tools/taco.cpp
This adds a simple parser function for command-line scheduling directives, based on Taco's existing expression parser features.  This allows more flexible use of whitespace, and better detection of mismatched parens.
Fixes: #349
This PR does the following:
* Remove trailing whitespace from `tools/taco.cpp`.
* Fix the `Index variable not defined in statement` error message to be reported properly to the user, and be more specific about the index variable and the statement.
* Add a schedule parser function, based on `Taco::Parser::Lexer`.
* Add test cases for the schedule parser function.
* Use the function in the taco command-line tool.
* Return usage messages when the user passes in the wrong number of parameters for a particular scheduling directive.
* Print an error when the user tries …
> Fix command-line schedule parsing

- src/error/error_checks.cpp
- src/error/error_checks.h
- src/index_notation/index_notation.cpp
Currently, there are two dimension checking methods in TACO. The first
returned a boolean, and the second returned a user readable string
detailing the error. Both methods had nearly identical code. Therefore,
this commit merges them into a single function that returns a boolean
and the error, if it exists.
> index_notation,error: deduplicate dimension checking routines

- src/lower/lowerer_impl.cpp
- test/tests-scheduling.cpp
Fixes #355.
This commit fixes a bug where the fuse transformation would not generate
necessary locator variables when applied to iteration over two dense
variables.
> lower: fix a bug causing undefined variables when applying fuse

- tools/taco.cpp
Adds the obvious `-help` option, which prints the same usage information that you get when running `taco` with no options or unrecognized options.
It also adds a `-help=scheduling` option, which prints a list of scheduling commands and descriptions.  The descriptions are mostly borrowed from the website.
Here's what the output looks like:
```
% bin/taco -help=scheduling
Scheduling commands modify the execution of the index expression.
The '-s' parameter specifies one or more scheduling commands.
Schedules are additive; more commands can be passed by separating
them with commas, or passing multiple '-s' parameters.
Examples:
-s="precompute(A(i,j)*x(j),i,i)"
-s="split(i,i0,i1,32),parallelize(i0,CPUThread,NoRaces)"
See http://tensor-compiler.org/docs/scheduling/index.html for more examples. …
```
> Schedule help

- include/taco/ir/ir.h
- include/taco/ir/ir_printer.h
- include/taco/ir/ir_rewriter.h
- include/taco/ir/ir_visitor.h
- src/codegen/codegen_cuda.cpp
- src/codegen/codegen_cuda.h
- src/ir/ir.cpp
- src/ir/ir_printer.cpp
- src/ir/ir_rewriter.cpp
- src/ir/ir_visitor.cpp
- src/lower/lowerer_impl.cpp
The current `ir::Break` statement actually translates to a `continue`.
This commit renames this to `ir::Continue`, and adds a new `ir::Break`
node that actually translates to a `break`. This new node will be used
by upcoming windowing work.
> include,src: introduce a true break statement, rename current to continue

- src/tensor.cpp
This fixes part of #366.  (The segfault on bad tensor names will be fixed separately.)
When data files are provided for all inputs, the `taco` command-line tool runs in "benchmark" mode, executing the generated code in-place.
This didn't quite work.  tensor.compileSource() didn't clear the needsCompile flag, causing the `tensor.assemble` step to complain.
> Clear the needsCompile flag in tensor.compileSource()

- src/storage/storage.cpp
- tools/taco.cpp
This fixes a few things related to the `-i` (input file) parameter of the command line tool.
Fixes:
1. The `TensorBase::TensorBase()` constructor sanity checks the number of format mode types, but this sanity check happens too late: `TensorStorage::Content()` segfaults before the check happens.
2. CLI tool doesn't reject input files with tensor names not mentioned in the expression
3. CLI tool doesn't create default formats of the correct sizes when loading tensors
These are fixed by:
1. copying the check into `TensorStorage::Content`.
2. pre-parsing the expression and making sure the tensor name is in there.
3. creating a `ModeFormat` vector of the right length, rather than the previous default (`Dense`).
There isn't a good framework in place to test the command-line tool, so I tested …
> Add an error message for invalid input tensor names.

- python_bindings/pybind11/include/pybind11/detail/common.h
- python_bindings/pybind11/include/pybind11/detail/internals.h
Fix two warnings in the python bindings.
`.../python_bindings/pybind11/include/pybind11/detail/internals.h:200:28: warning: ‘void PyEval_InitThreads()’ is deprecated [-Wdeprecated-declarations]`
This warning happens when building with python 3.9+.
`.../python_bindings/pybind11/include/pybind11/pybind11.h:1078:9: warning: expression result unused [-Wunused-value]`
This warning happens when building with clang 10+.
Both of these fixes are already present in later versions of pybind11:
https://github.com/pybind/pybind11/commit/fe1392d0895e7104aafe60f8bda17cd568d025e5
https://github.com/pybind/pybind11/commit/ae2ee2a4a51914cf78deb5c253a3b03cbb53ce72
> Fix warnings in python bindings

- include/taco/codegen/module.h
- src/codegen/module.cpp
- src/tensor.cpp
- test/tests-tensor.cpp
This commit fixes a bug where upon recompilation of an index statement,
entries in the kernel cache could be inadvertently modified, leading to
confusing segfaults.
An example of the bug is included in the added test, where the second
call to `c(i, j) = a(i, j)` would hit the cache, but then find a module
that had code that corresponded to `c(i, j) = a(i, j) + b(i, j)`.
> tensor,codegen: fix a bug where kernel cache could be modified

- src/codegen/codegen_cuda.cpp
- src/lower/lowerer_impl.cpp
Fix a few warnings that appear with `-DCMAKE_BUILD_TYPE=Release`.
```
/home/infinoid/workspace/taco/git/src/codegen/codegen_cuda.cpp: In member function ‘virtual void taco::ir::CodeGen_CUDA::visit(const taco::ir::Store*)’:
/home/infinoid/workspace/taco/git/src/codegen/codegen_cuda.cpp:1427:14: warning: unused variable ‘load’ [-Wunused-variable]
1427 |         auto load = to<Load>(add->a);
|              ^~~~
/home/infinoid/workspace/taco/git/src/codegen/codegen_cuda.cpp:1457:14: warning: unused variable ‘load’ [-Wunused-variable]
1457 |         auto load = to<Load>(bitOr->a);
|              ^~~~
/home/infinoid/workspace/taco/git/src/lower/lowerer_impl.cpp: In member function ‘virtual taco::ir::Stmt taco::LowererImpl::lowerForallFusedPosition(taco::Forall, taco::Iterator, …
```
> Fix warnings in Release builds

- test/tests-workspaces.cpp
Fixes: #380
gcc 5.4.0 has trouble deciding between `Tensor(..., Format)` and `Tensor(..., ModeFormat)`.  Give it an explicit cast.
> Fix workspaces test on ubuntu 16.04

- CMakeLists.txt
- README.md
There are some gaps in our test coverage.  This makes them visible.
This PR adds an easy way to run a code coverage analysis tool, showing you which parts of the code are being exercised by the test suite.  It requires the `gcovr` tool to be installed.  Its presence is detected during the config phase.
To use it:
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCOVERAGE=ON ..
make gcovr
google-chrome coverage/index.html
```
The index page looks like this:
Clicking on a filename gives you a line-by-line analysis.
> Add code coverage targets to cmake

- tools/taco.cpp
This bug was introduced in #352.
> Fix a bug in CLI parsing of bound()

- test/tests-scheduling-eval.cpp
This improves test coverage of suppressed atomics in openmp code.
It is a C++ API version of the example given here: https://github.com/tensor-compiler/taco/pull/401#issuecomment-777803611
I used the `spmvCPU_temp` test as a starting point for this, and I noticed some dead code (copypasta?).  I removed the dead code.
I also noticed that the C++ API doesn't have the same default loop order as the command line tool for this example.  I had to add a `.reorder({i,j,k})` call, otherwise the generated code refers to an index variable that hasn't been declared yet.  I will log that as a separate issue.
> Add a SpTV+openmp+atomics test case for #316

- include/taco/index_notation/index_notation.h
- include/taco/index_notation/index_notation_nodes.h
- include/taco/ir/ir.h
- include/taco/lower/iterator.h
- include/taco/lower/lowerer_impl.h
- include/taco/tensor.h
- src/codegen/codegen_c.cpp
- src/codegen/codegen_cuda.cpp
- src/error/error_checks.cpp
- src/index_notation/index_notation.cpp
- src/index_notation/index_notation_rewriter.cpp
- src/ir/ir.cpp
- src/lower/iterator.cpp
- src/lower/lowerer_impl.cpp
- src/tensor.cpp
- test/test.cpp
- test/test.h
- test/tests-windowing.cpp
This commit adds support for windowing of tensors in the existing index
notation DSL. For example:
```
A(i, j) = B(i(1, 4), j) * C(i, j(5, 10))
```
causes `B` to be windowed along its first mode, and `C` to be windowed
along its second mode. In this commit any mix of windowed and
non-windowed modes are supported, along with windowing the same tensor
in different ways in the same expression. The windowing expressions
correspond to the `:` operator to slice dimensions in `numpy`.
Currently, only windowing by integers is supported.
Windowing is achieved by tying windowing information to particular
`Iterator` objects, as these are created for each `Tensor`-`IndexVar`
pair. When iterating over an `Iterator` that may be windowed, extra
steps are taken to either generate an index into the …
> *: add support for windowing of tensors

- include/taco/lower/lowerer_impl.h
- src/lower/lowerer_impl.cpp
- test/tests-windowing.cpp
Fixes #409.
This commit fixes a bug where position loops parallelized with OpenMP
that operated over windowed tensor modes would fail to compile.
This commit also fixes some compilation errors compiling windowing tests
on Ubuntu.
> lower: fix a bug when using OpenMP and windowing

- CMakeLists.txt
This `add_subdirectory` line got removed somehow in #400, and I think it's still needed.  Without it, configuring with `-DPYTHON=ON` doesn't build Python bindings.
@RawnH , please review.
> Unbreak cmake build of python bindings

- include/taco/index_notation/index_notation.h
- include/taco/index_notation/index_notation_nodes.h
- include/taco/lower/iterator.h
- include/taco/lower/lowerer_impl.h
- src/error/error_checks.cpp
- src/index_notation/index_notation.cpp
- src/lower/iterator.cpp
- src/lower/lowerer_impl.cpp
- src/tensor.cpp
- test/tests-windowing.cpp
This commit extends the windowing syntax to include an optional third
parameter to a window expression on an index variable:
```
a(i) = b(i(0, n, 5 /* stride */))
```
This stride parameters means that the window should be accessed along
the provided stride, which defaults to 1.
Striding is implemented with a similar idea as windowing, where
coordinates in the stride are mapped to a canonical index space of `[0,n)`.
For compressed modes, coordinates that don't match the stride are
skipped.
> *: add the ability to stride window access

- .github/workflows/buildandtest.yml
Add a build step that covers the `OpenMP` and `Python` features.
Make it run `make test` to run all available test suites.  This invokes the googletest suite, which was previously run directly, as well as the Python test suite where python is enabled, and bash tests for the command-line tool when those become available (#393).
> Improve CI test coverage

- include/taco/index_notation/index_notation.h
- include/taco/index_notation/index_notation_nodes.h
- include/taco/lower/iterator.h
- include/taco/tensor.h
- src/error/error_checks.cpp
- src/index_notation/index_notation.cpp
- src/index_notation/index_notation_rewriter.cpp
- src/lower/iterator.cpp
- src/lower/lowerer_impl.cpp
- src/lower/merge_lattice.cpp
- src/tensor.cpp
- test/tests-windowing.cpp
This commit adds support for using vectors to index arbitrary dimensions
of tensors. It works by packing the vector into a sparse tensor, and
coiterating over the sparse tensor to efficiently filter the chosen
dimensions. The syntax of indexing sets look as follows:
```
A(i) = B(i({1, 3, 5}))
```
which means that only elements 1, 3, and 5 from `B` will be used in the
computation.
> *: add support for using arbitrary indexing sets to window tensors

- include/taco/index_notation/provenance_graph.h
- src/index_notation/index_notation.cpp
- src/index_notation/provenance_graph.cpp
- src/lower/lowerer_impl.cpp
- test/tests-scheduling.cpp
- tools/taco.cpp
The divide transformation divides a loop up into `n` equal components,
whereas split breaks a loop up into a components of size `n`.
> index_notation: implement the `divide` transformation

- src/index_notation/index_notation.cpp
- test/tests-index_notation.cpp
This commit has a temporary fix for a segfault encountered when the
`isomorphic` function is applied onto `IndexExpr`s that contain `Func`
applications. The casted pointer in `include/taco/util/functions.h:11`
that is dereferenced is `NULL`. This temporary fix is needed so that
benchmarking code can execute back-to-back iterations.
> index_notation: temporary fix for segfault with user defined funcs

- .github/workflows/buildandtest.yml
The CI tests currenty fail with:
```
Get:5 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 python3-olefile all 0.45.1-1 [33.3 kB]
Ign:6 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3-pil amd64 5.1.0-1ubuntu0.4
Get:7 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-scipy amd64 0.19.1-2ubuntu1 [9619 kB]
Err:6 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 python3-pil amd64 5.1.0-1ubuntu0.4
404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/pillow/python3-pil_5.1.0-1ubuntu0.4_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
Fetched 11.6 MB in 1s (23.0 MB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with …
```
> Fix package version issue in CI tests

- src/codegen/codegen_cuda.cpp
Fixes #422.
This commit ensures that the allocation clearing logic is applied to
the CUDA backend as well. The windowing test caught this because TACO
was automatically parallelizing the loop onto the GPU.
> cuda: fix windowing test with cuda

- include/taco/index_notation/index_notation.h
- src/index_notation/index_notation.cpp
- src/tensor.cpp
* Fixes a runtime error when using index sets on tensors not of integer types
* Fixes a compile error when using a vector typed variable as argument
for an index set.
> index_notation,tensor: small bugfixes for index sets

- tools/taco.cpp
The C++ scheduling API allows naming the workspace for `precompute()` calls.  The CLI tool always uses the name "workspace".
This patch adds an optional 4th parameter to the CLI `precompute()` directive, to specify the name of the workspace.  This makes it more consistent with the C++ API.  The patch also removes a debug message that was left in the CLI precompute code.
Here's an example with output:
```c
taco 'A(i) = B(i)*1 * C(i)' -s='precompute(B(i)*1,i,i,bi)' 
// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
int compute(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *C) {
int A1_dimension = (int)(A->dimensions[0]);
double* restrict A_vals = (double*)(A->vals);
int B1_dimension = (int)(B->dimensions[0]);
double* restrict B_vals = (double*)(B->vals);
int C1_dimension …
```
> Allow CLI precompute() to specify the workspace name

- tools/taco.cpp
I am constantly making the mistake of typing `--print-nocolor` instead of `-print-nocolor`, `--version` instead of `-version`, `--write-source` instead of `-write-source`.  This is my own fault, I'm too used to other command line tools that use `getopt_long` and take double hyphens for long options.  But it's a hard habit to break.
This patch detects two leading hyphens and ignores the first one.  The result is that TACO accepts both option passing styles.
Before:
```
% bin/taco 'a(i) = b(i)' --print-nocolor
Usage: taco <index expression> [options]
Examples:
taco "a(i) = b(i) + c(i)"                            # Dense vector add
taco "a(i) = b(i) + c(i)" -f=b:s -f=c:s -f=a:s       # Sparse vector add
[etc etc]
```
After:
```
% bin/taco 'a(i) = b(i)' --print-nocolor
// Generated by the …
```
> CLI tool treats double hyphens as a single hyphen

- src/lower/lowerer_impl.cpp
- test/tests-windowing.cpp
Fixes some formulaic errors in generated striding code along with a test
that revealed them.
> lowerer_impl: fix some striding bugs

- src/lower/merge_lattice.cpp
The code fixes to the array algebra iteration lattice construction algorithm. 
It is now passing all of the tests in `make test` and furthermore is creating the correct output for many other fused iteration spaces being tested in `tensor-compiler/array-programming-benchmarks`. 
I would like to add those fused benchmarks in as tests to `tests-merge_lattice.cpp` and `tests-lower.cpp` but will do that after 4/16/20
> Array algebra iter const

- src/lower/lowerer_impl.cpp
This improves error reporting in the case where the lowerer fails to emit guard conditions for unrolled/vectorized loops.
See #437 for examples of this.
Before:
```sh
$ bin/taco "a(i) = b(i) * c(i)" -s="parallelize(i,CPUVector,NoRaces)"
terminate called after throwing an instance of 'taco::TacoException'
what():  Compiler bug at /home/infinoid/workspace/taco/git/src/ir/ir.cpp:599 in make
Please report it to developers
Condition failed: then.defined()
Aborted
$ bin/taco "a(i) = b(i) * c(i)" -s="unroll(i,4)"
terminate called after throwing an instance of 'taco::TacoException'
what():  Compiler bug at /home/infinoid/workspace/taco/git/src/ir/ir.cpp:599 in make
Please report it to developers
Condition failed: then.defined()
Aborted
```
After:
```sh
$ bin/taco "a(i) = b(i) * c(i)" …
```
> Better error message for guarding unguardable loops

- include/taco/util/strings.h
The default precision when printing a floating point value is 6 digits.
This causes a lot of double values to get truncated. Print these with
full precision to avoid losing data.
> Use full precision when IR printing float constants

- include/taco/index_notation/index_notation.h
- src/index_notation/index_notation.cpp
- src/tensor.cpp
- test/tests-windowing.cpp
Fixes #451.
This commit fixes a bug where windows applied to index variables would
be dropped when assigned to via the `+=` operator.
> index_notation: fix a bug where windows would be dropped through `+=`

- CMakeLists.txt
- README.md
* Bump taco's cmake requirement to match pybind11's (3.4.0+).
* List minimum versions of gcc/clang (based on direct testing).
* Describe how to build taco with a specific compiler/version.
* Describe the python build deps in more detail; provide a list of debian/ubuntu packages.
* Mention clang's dependence on libomp headers/libs in openmp builds.
* Describe the minimum CUDA compute capability.
One thing this does *NOT* describe is the minimum NVidia driver/CUDA library versions.  I have not tested this, as I don't have an easy way to swap out different versions.
> Update minimum system requirements.

- src/index_notation/index_notation.cpp
- test/tests-scheduling.cpp
This PR addresses issues brought up in #431 and #347. Current behaviour of the precompute function generates incorrect code when `i != iw`. This can be fixed by not adding the children of precompute relations to the provenance graph.
**Testing:**
Added two test cases. First test case calls precompute with two different index variables. Second test case calls precompute with two different index variables before splitting the intermediary tensor to demonstrate that this fix does not impact subsequent transformations.
> Missing index variable declarations for precompute

- .github/workflows/buildandtest.yml
- .github/workflows/cuda-test-manual.yml
This PR adds github workflows to run the CUDA tests on a self-hosted runner.
Two workflows:
1. manually triggered
2. triggered by pushes to master
Once a self-hosted runner is set up, merging this will allow you to run tests on it.
Closes: #457
> Define CUDA CI actions

- include/taco/storage/typed_value.h
- src/storage/typed_value.cpp
- test/test-typedcomponent-memory.cpp
The pointer variant of `makeCSR()` can read past the end of the `pos` array.  In some (rare, unlucky) cases, this can cause the program to segfault.
The issue is that `TypedComponentRef::getAsIndex` does two 64-bit reads (of a 128-bit union type) and then passes (by value) down to the accessor method.  The solution is to pass a reference instead, so the accessor method only does a 32-bit read, and does not touch the other memory locations.
I also added a test case that carefully arranges memory to guarantee that out-of-bounds accesses will segfault.
Fixes: #455
Here's what valgrind says before the patch was applied:
```
valgrind --track-origins=yes ./test
==1009579== Memcheck, a memory error detector
==1009579== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1009579== …
```
> Clean up an invalid memory access in makeCSR()

- .github/workflows/buildandtest.yml
Github provides buildbots for MacOS, this adds it to our test workflow.
This adds a bit of much-needed variety; all of our other buildbots use gcc on Linux.
For the unfamiliar: `gcc` is a symlink to `clang` on MacOS, so no special build flags are required.
> Run CI tests on macos

- src/index_notation/transformations.cpp
- test/tests-workspaces.cpp
Fix a bug in the algorithm so that the precompute transformation can only occur on cascaded `ForallNodes` without any `WhereNodes` inside the `forall->stmt`. The current test `DISABLED_tile_dotProduct_1` tests this case but is currently disabled because of the issue stated in the test's comments/FIXME. 
Also fix a minor bug where `expected` and `A` were flipped in `test/tests-workspaces.cpp` when calling `ASSERT_TENSOR_EQ(expected, A)`.
Also added in some disabled precompute tests that **should** work but currently do not due to certain new bugs found in the algorithm. I would like to add these tests in to the regression disabled and track re-enabling them using Git issues.
> Fix some precompute transformation algorithm bugs that arose

- src/index_notation/index_notation.cpp
This fixes my use case, at least. I'm not sure where else this comparison is used. The tensor member gets read and written in a bunch of places, so I assume it's still needed.
> Don't check tensor when comparing IndexSets

- src/codegen/module.cpp
- test/tests-qcd.cpp
Relates to #373.
This commit adjusts the compilation command for generated code to
compile code with debug symbols when TACO is built in debug mode.
Conveniently, this allows for debuggers (like the integrated one in
CLion) to automatically display the generated source code when a
segfault occurs (along with other things the IDE supports).
> codegen: compile generated code with debug symbols in debug builds
